spring:
  datasource:
    url: jdbc:mysql://rm-wz98u82679y1eva2cno.mysql.rds.aliyuncs.com:3306/parking-alfred-dev?useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8082