spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parkinglot?useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8082

jwt:
  expire: 604800
  secret: zojoKieDTQYZXVi4dGKIn4qTkQA=